/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Serversock;

import java.awt.Color;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Chack
 */
public class ServerVisual extends javax.swing.JFrame {
    //ServerCode codigo;
    SocketCodes sc = new SocketCodes("sevidor-1", 5000);
    Thread tr = new Thread(sc);
    /**
     * Creates new form ServerVisual
     */
    public ServerVisual() {
        initComponents();
        setter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lserver = new javax.swing.JLabel();
        Lcliente = new javax.swing.JLabel();
        Tremote = new javax.swing.JLabel();
        Bstartstop = new javax.swing.JButton();
        Lstatus = new javax.swing.JLabel();
        Lip = new javax.swing.JLabel();
        Lipinterna = new javax.swing.JLabel();
        Lip2 = new javax.swing.JLabel();
        Lipexterna = new javax.swing.JLabel();
        Lp1 = new javax.swing.JLabel();
        Lpuerto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lserver.setText("Server");

        Lcliente.setText("Clientes: ");

        Tremote.setText("0.0.0.0");

        Bstartstop.setText("Iniciar");
        Bstartstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BstartstopActionPerformed(evt);
            }
        });

        Lstatus.setText("Offline");

        Lip.setText("IP Interna:");

        Lipinterna.setText("0.0.0.0");

        Lip2.setText("IP Externa:");

        Lipexterna.setText("0.0.0.0");

        Lp1.setText("Puerto:");

        Lpuerto.setText("00000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lip)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Lcliente)
                                    .addComponent(Lserver))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(Lstatus))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Lipinterna)
                                            .addComponent(Tremote)
                                            .addComponent(Lipexterna)
                                            .addComponent(Lpuerto)))))
                            .addComponent(Lip2)
                            .addComponent(Lp1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(Bstartstop)))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lserver)
                    .addComponent(Lstatus))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lcliente)
                    .addComponent(Tremote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lip)
                    .addComponent(Lipinterna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lip2)
                    .addComponent(Lipexterna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lp1)
                    .addComponent(Lpuerto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(Bstartstop)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BstartstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BstartstopActionPerformed
        // TODO add your handling code here:
        //SocketCodes.setPort(3000);

        if (Bstartstop.getText().equalsIgnoreCase("Iniciar")) {
            Lstatus.setText("Online");
            Lstatus.setForeground(Color.orange);
            Bstartstop.setText("Detener");
            Lpuerto.setText(sc.getPort() + "");
            SocketCodes.flagx = true;
            tr.start();

        } else {
            if (Bstartstop.getText().equalsIgnoreCase("Detener")) {
                System.out.println("Detener");
                Lstatus.setText("offline");
                Lstatus.setForeground(Color.BLACK);
                Bstartstop.setText("Iniciar");
                SocketCodes.flagx = false;
                //envio falso
                if (tr.isAlive()) {
                    SocketEnvio se = new SocketEnvio("localhost", 5000);
                    se.enviando(new Mp3Object());
                    try {
                        Thread.sleep(300);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(ServerVisual.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if (!tr.isAlive()) {
                        tr = new Thread(sc);
                        System.out.println("nuevo hilo " + tr.getName());
                    }
                }
            }
        }
    }//GEN-LAST:event_BstartstopActionPerformed

    public void setter() {
        //obteniendo ip
        try {
            InetAddress ips = InetAddress.getLocalHost();
            Lipinterna.setText(ips.getHostAddress());
            Lipexterna.setText("");
        } catch (UnknownHostException ex) {
            Logger.getLogger(ServerVisual.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bstartstop;
    private javax.swing.JLabel Lcliente;
    private javax.swing.JLabel Lip;
    private javax.swing.JLabel Lip2;
    private javax.swing.JLabel Lipexterna;
    private javax.swing.JLabel Lipinterna;
    private javax.swing.JLabel Lp1;
    private javax.swing.JLabel Lpuerto;
    private javax.swing.JLabel Lserver;
    private javax.swing.JLabel Lstatus;
    private javax.swing.JLabel Tremote;
    // End of variables declaration//GEN-END:variables
}
